# https://leetcode.com/problems/find-the-difference/
# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_list = list(s)
        for el in t:
            if el in s_list:
                s_list.remove(el)
            else:
                return el

if __name__=="__main__":
    obj = Solution()
    param_1 = obj.findTheDifference("abcd", "abcde")
    print(param_1)